apiVersion: batch/v1
kind: Job
metadata:
  name: client
spec:
  template:
    spec:
      containers:
        - name: hello
          image: busybox:1.28
          command: ["/bin/sh", "-c", "echo Hello, world!"]
      restartPolicy: OnFailure
  backoffLimit: 5
