apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: resource-model
spec:
  containers:
    - image: nginx
      name: resource-model
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
