apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: myservice
  type: ClusterIP
status:
  loadBalancer: {}
