apiVersion: v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-troubleshoot
  name: nginx-troubleshoot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-troubleshoot-pod
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-troubleshoot
    spec:
      containers:
        - image: nginx:1.13
          name: nginx
          resources: {}
status: {}
