apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: demo2-nginx-02
spec:
  containers:
    - image: nginx:alpine
      name: demo2-nginx-02
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
