apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: hostpath
      image: alpine
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do ls -la /data; echo; sleep 5; done"
      volumeMounts:
        - name: my-volume
          mountPath: /data
  volumes:
    - name: my-volume
      hostPath:
        path: /tmp/node-data
