apiVersion: v1
kind: Pod
metadata:
  name: pod-with-configmap
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: SERVER
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: server
