version: '3.8'

services:
  # Data base config
  database:
    container_name: ${db_container}
    image: ${db_image}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${db_root_pass}
      MYSQL_DATABASE: ${db_database}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_pass}
    expose:
      - 3306
    volumes:
      - ${db_volume}:/var/lib/mysql
    networks:
      - ${net}
  # I thinks this will database interface
  phpmyadmin:
    depends_on:
      - database
    image: ${php_image}
    container_name: ${php_con}
    restart: always
    ports:
      - "${php_port}"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${db_root_pass}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_pass}
    networks:
      - ${net}
  # FE container that will be user interface
  wordpress:
    depends_on:
      - database
    container_name: ${fe_container}
    image: ${fe_image}
    ports:
      - "${fe_port}"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: ${db_user}
      WORDPRESS_DB_PASSWORD: ${db_pass}
      WORDPRESS_DB_NAME: ${db_database}
      APACHE_SERVER_NAME: ${apache_server_name}
    volumes:
      - ${fe_volume}:/var/www/html
    networks:
      - ${net}

networks:
  a01:
volumes:
  wordpress_data:
  db_data:
