# kubectl apply -f Configmap-secret-day5.yaml
# Pod Config map
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-config-map # pod name
#  labels:
#    name: myapp
spec:
  containers:
    - name: con-nginx-config-map # container name
      image: nginx:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      #    ports:
      #      - containerPort: <Port>
      env:
        - name: COURSE # take value from learn data in configmap file
          valueFrom:
            configMapKeyRef:
              name: day5-config-map
              key: learn
        - name: SESSION # take value from session data in configmap file
          valueFrom:
            configMapKeyRef:
              name: day5-config-map
              key: session

---
# Config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: day5-config-map
data:
  learn: K8s-testing-is-some-thing-trying-too-code
  session: "123456789"

---
# Pod 2 with secret
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-secret # name pod
#  labels:
#    name: myapp
spec:
  containers:
    - name: con-nginx-secret # name container
      image: nginx:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      #      ports:
      #        - containerPort: <Port>
      env:
        - name: USERNAME # Take user name value from secret
          valueFrom:
            secretKeyRef:
              name: day5-secret
              key: username
        - name: PASSWORD # Take password value from secret
          valueFrom:
            secretKeyRef:
              name: day5-secret
              key: password
---
# Secret file
apiVersion: v1
kind: Secret
metadata:
  name: day5-secret
type: Opaque
data:
  username: ZHVvbmd0bg== # Mã hóa Base64 của "duongtn"
  password: ZHVvbmcxMjM0NQ== # Mã hóa Base64 của "duong12345"
