apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: issue-box
  name: issue-box
spec:
  containers:
    - image: busybox
      name: issue-box
      command: ["/bin/sh", "-c", "sleeeep 3600"]
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
