# Apply the configuration defined in this YAML file using the kubectl apply command
# kubectl apply -f pod-day3.yaml

# Pod on First Node (control-plane node)
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-node1 # The name of the pod
  labels:
    app: nginx
spec:
  nodeName: duong1-worker # Specify the name of the control-plane node
  containers:
    - name: container-node1-nginx # Name of the container
      image: nginx:alpine # Use the official Nginx image
      resources:
        limits:
          cpu: "0.5" # Limit CPU usage to 0.5 CPU cores
          memory: "512Mi" # Limit memory usage to 512 megabytes
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd-node1 # The name of the http pod
  labels:
    app: httpd
spec:
  nodeName: duong1-worker2 # Specify the name of the control-plane node
  containers:
    - name: container-node1-httpd # Name of the container
      image: httpd # Use the official httpd image
      resources:
        limits:
          cpu: "0.5" # Limit CPU usage to 0.5 CPU cores
          memory: "512Mi" # Limit memory usage to 512 megabytes
