version: '3'
services:
  # nginx container and enviroment config 
  nginx:
    image: ${nginx_image}
    container_name: ${nginx_container}
    volumes:
      - ${bind_dir}:${nginx_html}
    ports:
      - "${nginx_port}"
    networks:
      - task_02
  # httpd container and enviroment config
  httpd:
    image: ${http_image}
    container_name: ${http_conatainer}
    volumes:
      - ${bind_dir}:${http_html}
    ports:
      - "${http_port}"
    networks:
      - task_02
# network use for 2 container
networks:
  task_02:
