# kubectl apply -f deployment-nginx.yaml --namespace this-is-nginx-space

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: duong1-control-plane # Specify the name of the control-plane node
      containers:
        - name: container-node1-nginx # Name of the container
          image: nginx:alpine # Use the official Nginx image
          ports:
            - containerPort: 80 # Nginx uses port 80
          resources:
            limits:
              cpu: "0.5" # Limit CPU usage to 0.5 CPU cores
              memory: "512Mi" # Limit memory usage to 512 megabytes
      initContainers: # Add the initContainers section for defining init containers.
        - name: init-container-demo # Name of the init container.
          image: busybox:latest # Use a simple BusyBox image as an example.
          command: ["sh", "-c", "echo 'Init Container is running!'"] # Specify the init container command.

