# kubectl apply -f deployment-nginx.yaml --namespace this-is-nginx-space
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # The name of the Deployment is "nginx-deployment."
spec:
  replicas: 2 # The desired number of replica Pods is 2.
  selector:
    matchLabels:
      app: nginx # Select Pods with the label "app: nginx" to manage.
  template:
    metadata:
      labels:
        app: nginx # Label the Pods managed by this Deployment with "app: nginx."
    spec:
      nodeName: duong1-control-plane # Specify the name of the control-plane node where the Pods should run.
      containers:
        - name: container-node1-nginx # Name of the container is "container-node1-nginx."
          image: nginx:alpine # Use the official Nginx image from Docker Hub.
          ports:
            - containerPort: 80 # Expose port 80 within the container.
          resources:
            limits:
              cpu: "0.5" # Set a CPU limit of 0.5 CPU cores for this container.
              memory: "512Mi" # Set a memory limit of 512 megabytes for this container.
      initContainers: # Add an initContainers section to define an init container.
        - name: init-container-demo # Name of the init container is "init-container-demo."
          image: busybox:latest # Use the latest BusyBox image as an example.
          command: ["sh", "-c", "echo 'Init Container is running!'"] # Specify the init container command.
