# kind create cluster --name duong1 --config kind-config.yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080 # Change the host port to an available port
        protocol: TCP
      - containerPort: 443
        hostPort: 8443 # Change the host port to an available port
        protocol: TCP
