# kubectl apply -f deployment-nginx.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-nginxport-service
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - port: 2000
      targetPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-nginxport-service
# spec:
#   selector:
#     app: nginx
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 30080
