# kubectl apply -f app-deploy.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-httpdport-service
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginxport-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
